"""Export utilities for various output formats."""

from __future__ import annotations

import json
from pathlib import Path
from datetime import datetime, timezone


def export_markdown(content: str, metadata: dict, output_path: str | Path) -> Path:
    """Export content as Markdown with YAML front matter."""
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)

    fm_lines = ["---"]
    for key, value in metadata.items():
        if isinstance(value, list):
            fm_lines.append(f"{key}:")
            for item in value:
                fm_lines.append(f"  - {item}")
        else:
            fm_lines.append(f"{key}: {value}")
    fm_lines.append("---")
    fm_lines.append("")

    output.write_text("\n".join(fm_lines) + content)
    return output


def export_html(content: str, metadata: dict, output_path: str | Path) -> Path:
    """Export content as semantic HTML5."""
    import re

    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)

    title = metadata.get("title", "Untitled")
    description = metadata.get("description", "")
    author = metadata.get("author", "ContentForge")
    date = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    # Simple Markdown to HTML conversion
    html_body = content
    html_body = re.sub(r"^### (.+)$", r"<h3>\1</h3>", html_body, flags=re.MULTILINE)
    html_body = re.sub(r"^## (.+)$", r"<h2>\1</h2>", html_body, flags=re.MULTILINE)
    html_body = re.sub(r"^# (.+)$", r"<h1>\1</h1>", html_body, flags=re.MULTILINE)
    html_body = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", html_body)
    html_body = re.sub(r"\*(.+?)\*", r"<em>\1</em>", html_body)
    html_body = re.sub(r"^(?!<h|<strong|<em)(.+)$", r"<p>\1</p>", html_body, flags=re.MULTILINE)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{description}">
    <meta name="author" content="{author}">
    <meta property="og:title" content="{title}">
    <meta property="og:description" content="{description}">
    <title>{title}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
               max-width: 800px; margin: 0 auto; padding: 2rem; line-height: 1.6; }}
        h1 {{ font-size: 2rem; margin-bottom: 0.5rem; }}
        h2 {{ font-size: 1.5rem; margin-top: 2rem; }}
        article {{ margin-top: 2rem; }}
        meta {{ color: #666; font-size: 0.9rem; }}
    </style>
</head>
<body>
    <header>
        <h1>{title}</h1>
        <meta>By {author} | {date}</meta>
    </header>
    <article>
        {html_body}
    </article>
    <footer>
        <p><em>Generated by ContentForge v1.0 — provider-agnostic AI content pipeline</em></p>
    </footer>
</body>
</html>"""

    output.write_text(html)
    return output


def export_json_report(metrics: dict, output_path: str | Path) -> Path:
    """Export pipeline metrics as JSON report."""
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(metrics, indent=2, ensure_ascii=False))
    return output
